version: "2"

services:

  steedos:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /srv/workflow/cfs:/storage
      - /srv/git/steedos-sap-plugin/steedos-config.yml:/app/steedos-config.yml
    environment:
      - SAPNWRFC_HOME=/app/nwrfcsdk/linux

