version: "2"

services:

  steedos:
    build: .
    restart: unless-stopped
    ports:
      - "5040:5000"
    volumes:
      - /srv/workflow/cfs:/storage
      - /srv/git/steedos-sap-plugin/steedos-config.yml:/app/steedos-config.yml


# volumes:
#   # Storage for attachments
#   steedos-storage-1:
#   mongo-db-1:
#   mongo-backup-1:
