env:
  PORT: 5000
  ROOT_URL: http://127.0.0.1:5000
datasources:
  default:
    connection:
      url: mongodb://127.0.0.1/steedos
    objectFiles:
      - "./src"
    appFiles:
      - "./src/SAP.app.yml"
public:
  cfs:
    store: "local"
    local:
      folder: "/storage"
cron:
  sap_sync_interval: 10000