env:
  PORT: 5000
  ROOT_URL: http://127.0.0.1/sap/
datasources:
  default:
    connection:
      url: mongodb://127.0.0.1/steedos
    objectFiles:
      - "./src"
    appFiles:
      - "./src/SAP.app.yml"
public:
  cfs:
    store: "local"
    local:
      folder: "/storage"
  webservices:
    workflow:
      url: "http://127.0.0.1/"
cron:
  -sap_sync_rule: "0 03 * * * *"
  -sap_get_draft_rule: "0 15 * * * *"
plugins:
  sap:
    abapConfig:
      user: 'xxxx'
      passwd: '123456'
      ashost: '172.172.172.172'
      sysnr: '00'
      client: '300'
      lang: 'ZH'
    spaceId: 'p9s45jNmhRkyCnjpi'
    flows:
      yongkuandan: '468b4caded61e2a13b89027c'
      wuliao: '73c38583e4afff48aba584c6'
