env:
  PORT: 5000
  ROOT_URL: http://127.0.0.1:5000
datasources:
  default:
    connection:
      url: mongodb://127.0.0.1/steedos
    objectFiles:
      - "./src"
    appFiles:
      - "./src/SAP.app.yml"
public:
  cfs:
    store: "local"
    local:
      folder: "/storage"
cron:
  -sap_sync_rule: "0 * * * *"
  -sap_get_draft_rule: "0 * * * *"
plugins:
  sap:
    abapConfig:
      user: 'xxxxxx'
      passwd: '123456'
      ashost: '172.172.172.172'
      sysnr: '00'
      client: '300'
      lang: 'ZH'
    spaceId: 'xxxxxxxxxxxx'
    flows:
      yongkuandan: 'flowId'
      wuliao: 'flowId'
